### ISSUE TITLE
Unable to call jQuery(document).ready() from Lua

### ISSUE THREAD

**Issue by ghost** [daurnimator/lua.vm.js#15]
Hello,

First of all, let me tell you that this project is super exciting! I am working on server-side Lua proramming (LSP), but being able to write client-side scripting in Lua without any pre-compilation (unlike the Moonshine project) is a big plus! Please keep maintaining and improving this project. It has a tremendous amount of potential, as porting Lua to essentially all web browsers opens up a world of possibilities!

I was testing whether I could re-use jQuery without having to re-write it in Lua completely. Using the $ variable doesn't work, probably because this is an invalid variable name in Lua. Luckily, jQuery provides a global variable called jQuery, so simple things like js.global.jQuery("#divid").html("This is JQuery from Lua!!!") work fine.  However, js.global.jQuery(js.global.document).ready(function() ... end) doesn't work, giving a cryptic "SyntaxError" error on lua.vm.js:6624.

I suspect this maybe because I'm trying to pass a Lua function object to a JavaScript function that expects a JS function object, and this conversion may not be supported. Any thoughts?

Regards,

Gabriel Mongefranco
Software Developer
http://gabriel.mongefranco.com

**Comment by joelpinheiro** [comment]
Is it possible to call from NodeJS?

Certain with a different approach from `window.jQuery`.
