### ISSUE TITLE
Unable to Call HTTP Request Methods from NodeJS

### ISSUE THREAD

**Issue by joelpinheiro** [daurnimator/lua.vm.js#46]
Hello,

```lua
local jq = window.jQuery()
print("version", jq.jquery)
print("version second call", jq.jquery)
local jqxhr = window.jQuery:get("/glossary.json")
jqxhr:done(function() print(jqxhr.responseText) end)
```

Since there isn't the Window object in NodeJS how can I call JQuery ajax get/post in lua.vm.js?

```lua
local jq = js.get("$")
local jqxhr = jq.get("/glossary.json")
jqxhr.done(function() print(jqxhr.responseText) end)
```

I had tried the code above that catch the follow exception:
`e:Lua.Error: [string "?"]:5: attempt to call field 'get' (a nil value)`

**Comment by daurnimator** [comment]
`local jq = js.get("$")`
That doesn't make any sense. Did you mean:
`local jq = js.global["$"]`

**Comment by joelpinheiro** [comment]
Thank you, daurnimator.

'local jq = js.global["$"]
local jqxhr = jq.post("...")'

The code above returns the following exception:
e:Lua.Error: [string "?"]:6: attempt to index local 'jq' (a nil value)

**Comment by daurnimator** [comment]
> e:Lua.Error: [string "?"]:6: attempt to index local 'jq' (a nil value)

do you have a `$` global in the javascript vm?

**Comment by joelpinheiro** [comment]
Truly, I don't know. But from I get of lua.js I don't have it.

**Comment by daurnimator** [comment]
Well if you don't load jquery into `$`, who else will?

**Comment by joelpinheiro** [comment]
How can I create a `$` global in javascript vm?
After creating it, there is a way to load jquery to it?

My goal is to do this:
`local jq = window.jQuery()
print("version", jq.jquery)
print("version second call", jq.jquery)
local jqxhr = window.jQuery:get("/glossary.json")`

But using only NodeJS (without window/document object).

**Comment by joelpinheiro** [comment]
I had created a JS function that imports JQuery and then execute the HTTP Request.

   ```
     var LuaVM = require('lua.vm.js');
        var l = new LuaVM.Lua.State();
        
        lua_script = JSON.parse(lua_script);
        
        lua_script = lua_script.replace("local jq = window.jQuery()","");
        lua_script = lua_script.replace("local jqxhr = window.jQuery:post(url)","js.global:executeJQuery(url)");
        
       
        function executeJQuery(x) {
            
            console.log("executeJQuery...");
            
            require("jsdom").env("", function(err, window) {
                if (err) {
                    console.error(err);
                    return;
                }
            
                var $ = require("jquery")(window);
                
                $.ajax({
                    type: "POST",
                    url: x,
                    success: function (result) {
                        if (result.isOk == false) alert(result.message);
                    }
                });
            });
        };
        
        try {
        l.execute(lua_script);
        console.log("Executed lua_script: " + lua_script);
        } catch(e) {
        console.log("e:" + e)
        }
```

The lua_script:
```
lua_script:    -- STOCK --
function stock_limit(SYMBOL, EXCHANGE, CURRENCY, ACTION, QUANTITY, PRICE)
  	ORDERTYPE = 'limit'
  	ACTIONX = 'stock'
  	local url = "http://localhost:1337/node_ib_api?ORDERTYPE=" .. ORDERTYPE .. "&ACTIONX=" .. ACTIONX .. "&SYMBOL=" .. SYMBOL .. "&EXCHANGE=" .. EXCHANGE .. "&CURRENCY=" .. CURRENCY .. "&ACTION=" .. ACTION .. "&QUANTITY=" .. QUANTITY .. "&PRICE=" .. PRICE .. "&LIMITPRICE=" .. LIMITPRICE .. "&STOPPRICE=" .. STOPPRICE

 	js.global:executeJQuery(url)
  	jqxhr:done(function() print(jqxhr.responseText) end)
end
```

But, when I call `js.global:executeJQuery(url)` I receive the following error:
`e:Lua.Error: [string "?"]:7: attempt to call method 'executeJQuery' (a nil value)`

Am I calling it wrong? Should I define executeJQuery elsewhere?

**Comment by daurnimator** [comment]
I don't think that creates `executeJQuery` as a global.

However, that js code, you can just run from lua:
```lua
local jq = js.global:require("jquery")
```

**Comment by joelpinheiro** [comment]
I need an extra file and use 'GLOBAL._ = require('executeJQuery')', and then GLOBAL.executeJQuery(url). It's this the proper way to create a global in lua.vm?

**Comment by daurnimator** [comment]
> I need an extra file and use 'GLOBAL._ = require('executeJQuery')', and then GLOBAL.executeJQuery(url).

Huh? No.
What is this `GLOBAL` variable you refer to.
Why are you assigning to `GLOBAL._`?
Is that JS code or Lua code?

> It's this the proper way to create a global in lua.vm?

You can just do: `myluastate._G.set("myluaglobal", "value")`

but.... why are you trying to set a global in the first place?

**Comment by joelpinheiro** [comment]
I had created a new module in different JS file:
```
module.exports =  {

    executeJQ : function(x) {
            
            console.log("executeJQuery");
            
            require("jsdom").env("", function(err, window) {
                if (err) {
                    console.error(err);
                    return;
                }
            
                var $ = require("jquery")(window);
            
            
                console.log("x: " + x);
                
                console.log("Resultado: \n\n")
                
                $.ajax({
                    type: "POST",
                    url: x,
                    success: function (result) {
                        
                        console.log(result.message)
                        //if (result.isOk == false) console.log(result.message);
                    }
                });
            });
        }
}
```

In LUA I tried to use:
`local jq = js.global:require("executeJQuery.js")`

But, I'm receiving `e:Lua.Error: [string "?"]:6: attempt to call method 'require' (a nil value)`

**Comment by daurnimator** [comment]
I've commited a fix for #31. does your code work now?

**Comment by joelpinheiro** [comment]
I updated my node_module from NPM:
`npm install lua.vm.js`

My code:
```
local JQ = js.global:require"./executeJQuery.js"
JQ:executeJQuery("www.google.com")
```

Ex:
`e:Lua.Error: [string "?"]:5: attempt to call method 'require' (a nil value)`

**Comment by daurnimator** [comment]
See https://github.com/daurnimator/lua.vm.js/issues/57#issuecomment-235422400
