### ISSUE TITLE
Question about AddEventListener and general callbacks

### ISSUE THREAD

**Issue by MangelMaxime** [daurnimator/lua.vm.js#55]
Hello I am trying to prevent a form to be submit.
Here is my code. 

```lua
function init()
  local form = document:querySelector(".to-validate")
  if notNullJs(form) then

    form:addEventListener(
      "submit",
      function (event)
        print(event)
        event:preventDefault()
      end,
      false)
  end
end
```

When I submit the form, I always got this error: `Lua.Error: [string "validator.lua"]:12: attempt to call method 'preventDefault' (a nil value)`

Can you explain me what I am doing wrong ? And also, if this is possible to define the callback as a standard function outside of `addEventListener`

**Comment by daurnimator** [comment]
> When I submit the form, I always got this error: Lua.Error: [string "validator.lua"]:12: attempt to call method 'preventDefault' (a nil value)
>
> Can you explain me what I am doing wrong ?

The first argument to your callback will be the `this` for that function.

> And also, if this is possible to define the callback as a standard function outside of addEventListener

Sure is:

```lua
local function onsubmitted(this, event)
    event:preventDefault()
end

function init()
  local form = document:querySelector(".to-validate")
  if notNullJs(form) then
    form:addEventListener("submit", onsubmitted, false)
  end
end
```
