### ISSUE TITLE
Require from folder outside of project on Windows

### ISSUE THREAD

**Issue by jfmmm** [daurnimator/lua.vm.js#57]
I'm executing a lua file from a game in another folder on Windows that is outside of my project folder.

I added the game folder with this lua code so it knows where to find the files that the main file require:
`package.path = package.path .. ";C:/Program Files (x86)/Steam/steamapps/common/Factorio/data/core/?.lua"`

When I execute that lua file it thrown an error at the first require it encounter : 

```
[string "?"]:1: module 'prototypes.fonts' not found:
        no field package.preload['prototypes.fonts']
        no file '/usr/local/share/lua/5.2/prototypes/fonts.lua'
        no file '/usr/local/share/lua/5.2/prototypes/fonts/init.lua'
        no file '/usr/local/lib/lua/5.2/prototypes/fonts.lua'
        no file '/usr/local/lib/lua/5.2/prototypes/fonts/init.lua'
        no file './prototypes/fonts.lua'
        no file 'C:/Program Files (x86)/Steam/steamapps/common/Factorio/data/core/prototypes/fonts.lua'
        no file '/usr/local/lib/lua/5.2/prototypes/fonts.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './prototypes/fonts.so'
        no file '/usr/local/lib/lua/5.2/prototypes.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './prototypes.so'
```

except one of the path it thrown as not working is exactly where the file it need to include is located.

this one :
`no file 'C:/Program Files (x86)/Steam/steamapps/common/Factorio/data/core/prototypes/fonts.lua'`

So why won't it work then?

**My code :**

```
var fs          = require('fs');
var path        = require('path');

/* LUA VM */
var LuaVM       = require('lua.vm.js');
luaState    = new LuaVM.Lua.State();

/* FACTORIO Install location path */
var gamePath    = 'C:/Program Files (x86)/Steam/steamapps/common/Factorio/';

// factorio/data/
var dataPath    = path.join(gamePath, 'data/');
// factorio/data/core/
var corePath    = path.join(dataPath, 'core/');
// factorio/data/base/
var basePath    = path.join(dataPath, 'base/');

/* add factorio core folder to the lua package path */
runLua('package.path = package.path .. ";' + corePath.replace(/\\/g,'/') + '?.lua"');

/* run "factorio/data/core/data.lua" */
runLua(fs.readFileSync(path.join(corePath, 'data.lua'), "utf8"));

function runLua(code){
  try{
    luaState.execute(code);
  }catch(e){
    console.log(e.message);
  }
}
```

**The lua file im trying to run :**
```
require("prototypes.fonts")
require("prototypes.style")
require("prototypes.utility-sprites")
require("prototypes.noise-layers")
```

Thanks!

**Comment by daurnimator** [comment]
lua.vm.js uses a virtual file system (as provided by emscripten). it does not use your real file system.

**Comment by jfmmm** [comment]
So how can I do what I'm trying to achieve? do I have to more the file in my project?

**Comment by daurnimator** [comment]
> So how can I do what I'm trying to achieve? do I have to more the file in my project?

You'll need to hook things up to your real file system.
e.g. add a function to `package.searchers` that uses node.js's `fs` module.

On the other hand.... what are you trying to do? Why are you trying to load some game's lua code into a node.js instance? Why not just use lua itself?

**Comment by jfmmm** [comment]
well first I would like to code as little lua as possible :\

It's a c++ game that store all it's data (prototype, locale, tiles, recipes, technologies, etc.) inside unencrypted lua files in the game folder. So I want to execute those lua file and then export the table to .json so I can make graphs with the data.

That would be extremely complicated for me to do in Lua, but I know web development very well so I would rather do that with node.

-----

So if I was instead to run a express server along side and serve all the game folder onto localhost:3000, I could use require to do it right?

```
require "http://localhost:3000/static/core/data.lua"
require "prototypes.fonts"  
```

It would get that I mean `http://localhost:3000/static/core/prototypes/fonts.lua` ?

**Comment by jfmmm** [comment]
> e.g. add a function to package.searchers that uses node.js's fs module.

I didn't find much help on how to do that, what do I need to return from this function exactly?

I found this but I'm not sure what it need to return (the loader function)
https://gist.github.com/stevedonovan/1297868

```
package.searchers[5] = function (name)
   //do stuff with node fs

   return loader, modpath
end
```

**Comment by daurnimator** [comment]
> I could use require to do it right?

You can load files with things other than `require`. `require` is normally used for modules/libraries.

Write some lua code that uses node's `fs` module to read the lua file, the load it with lua's `load()` function.

**Comment by jfmmm** [comment]
The plan is to not have to change the game lua file, and they use require. So i'm stuck with that.

**Comment by daurnimator** [comment]
Okay. so you need to write a `package.searcher`. See http://www.lua.org/manual/5.2/manual.html#pdf-package.searchers

Something like:
```lua
table.insert(package.searchers, function(name)
    local path = package.searchpath(name, "C:/Program Files (x86)/Steam/steamapps/common/Factorio/?.lua")
    if not path then return nil end
    local contents = js.global.require("fs").readFileSync(path)
    return load(contents, "@"..path), path
end)
```

**Comment by jfmmm** [comment]
the require('fs') part return me an errror

`attempt to call field 'require' (a nil value)`

**Comment by daurnimator** [comment]
That sounds like the same issue this guy ran into: https://github.com/daurnimator/lua.vm.js/issues/46#issuecomment-196888206

I'm not sure why `require` isn't in the global js scope.

**Comment by jfmmm** [comment]
yeah that's what I found.. 

this seem to work after I declared my "fs" variable in JS as global, not sure why the first argument of readFileSync is ignored tho, is it because lua array start a 1 instead of 0 like in JS?

I had to specify utf8, so it load a string instead of a buffer.

```
table.insert(package.searchers, function(name)
    local path = "C:/Program Files (x86)/Steam/steamapps/common/Factorio/data/core/"..name:gsub("%.", "/")..".lua"

    local contents = js.global.fs.readFileSync(null, path, "utf8")
    return load(contents, "@"..path), path
end)
```

anyway thanks for the quick help, greatly appreciated :)

**Comment by daurnimator** [comment]
> this seem to work after I declared my "fs" variable in JS as global, not sure why the first argument of readFileSync is ignored tho, is it because lua array start a 1 instead of 0 like in JS?

The first argument to js functions from lua.vm.js is `this`. Usually you call with lua's method syntax (using `:`). Change your code to: `js.global.fs:readFileSync(path, "utf8")`

**Comment by jfmmm** [comment]
it work thanks!

**Comment by daurnimator** [comment]
After research with help from @creationix we found https://nodejs.org/dist/latest-v6.x/docs/api/process.html#process_process_mainmodule

This means you can use js's require with:

```lua
js.global.process.mainModule:require("fs")
```

Additionally, many of the node builtin modules don't actually need to be required (the ones in this list: https://github.com/nodejs/node/blob/e22ffefff221caee264ab0b88691478a03ab1862/lib/internal/module.js#L54-L57) which means you can just use `js.global.fs` anyway.

**Comment by jfmmm** [comment]
no js.global.fs only work if I add `fs = require('fs');` in my code.

I get this if I don't 

`attempt to index field 'fs' (a nil value)`

**Comment by jfmmm** [comment]
weither I do this
`js.global.process.mainModule.require("fs"):readFileSync(path, "utf8")`
or this
`js.global.process.mainModule.require("fs"):readFileSync(path, "utf8")`

I have to add the null again to get it to work, what is the right syntax?
`readFileSync(this, path, "utf8")`

**Comment by creationix** [comment]
The auto-globals in node.js are non-enumerable getter properties.  Does the
bridge not expose these kinds of properties to lua?

**Comment by daurnimator** [comment]
> weither I do this
> js.global.process.mainModule.require("fs"):readFileSync(path, "utf8")
> or this
> js.global.process.mainModule:require("fs").readFileSync(path, "utf8")
> 
> I have to send null as the first argument again to get it to work, what is the right syntax?
> readFileSync(null, path, "utf8")

You need to use the method call syntax when calling a method.
i.e.
```lua
js.global.process.mainModule:require("fs"):readFileSync(path, "utf8")
```
  - `require` is a method on a module
  - `readFileSync` is a method on the `fs` library.
