### ISSUE TITLE
Is it possible to bundle compiled modules, such as LPeg with lua.vm.js ?

### ISSUE THREAD

**Issue by saucisson** [daurnimator/lua.vm.js#63]
In a project, i need LPeg, but it is not pure Lua code. Lulpeg (the pure Lua equivalent) has a huge performance drawback.

So, is it possible to bundle compiled modules, such as LPeg with lua.vm.js ? If yes, how can i do it ?

**Comment by daurnimator** [comment]
> So, is it possible to bundle compiled modules, such as LPeg with lua.vm.js ? If yes, how can i do it ?

Same as you would compile a statically compile in a library with normal lua:
  - compile lpeg object files
  - add your object files to the final link (via adding to [MYOBJS](https://github.com/daurnimator/lua.vm.js/blob/4e3fd0341205b6bdecf74de80ea94e5d5e53013a/lua/src/Makefile#L25)
  - use `luaL_requiref` to call the library entry point. e.g. via adding to [linit.c](https://github.com/daurnimator/lua.vm.js/blob/4e3fd0341205b6bdecf74de80ea94e5d5e53013a/lua/src/linit.c#L29)

**Comment by saucisson** [comment]
Thanks, it works great. In case someone else reads this ticket, here is a repository with lua.vm.js and lpeg bundled together: https://github.com/saucisson/lua.vm.js-lpeg.
