### ISSUE TITLE
setfenv() analog?

### ISSUE THREAD

**Issue by egordorichev** [daurnimator/lua.vm.js#65]
Hello!
I need to create a lua environment, that has nothing but defined by me functions. In pure lua I would implement that using `setfent()`:

```lua
setfenv(f, {
 print = api.print,
 cls = api.cls,
 ...
})
```

Is there a way to do the same thing with lua.vm.js? Thanks!

**Comment by daurnimator** [comment]
lua.vm.js is just lua 5.2: you can use `load` and `_ENV` in 5.2 to do similar things to `setfenv`.

However, lua.vm.js also makes you make completely independent states. Use `new Lua.State();` (from JS) to get a new lua state.

**Comment by egordorichev** [comment]
Hmm, I'm really sorry! Like this? 
```lua
	cart.lua.execute("_ENV['printh'] = ...; printh('test')", console.log)
```

Doesn't seem to work.
It works, if I pass console object:

```lua
cart.lua.execute("local printh = ...; printh:log('test')", console)
``` 
But I need a function, not an object.

**Comment by daurnimator** [comment]
`cart.lua.execute("local _ENV = (...); printh:log('test')", {printh = console})`

Instead of using `execute` you can do it programatically too.

**Comment by egordorichev** [comment]
Can I ask, how? Thanks :D

**Comment by daurnimator** [comment]
Take a look at the source of execute: https://github.com/daurnimator/lua.vm.js/blob/4e3fd0341205b6bdecf74de80ea94e5d5e53013a/src/lua.js#L553

You'll want to do the same thing but use `lua_setupvalue` just after the `loadbufferx` call (which is inside of the `load` method).

**Comment by egordorichev** [comment]
Hmm, I'm not familiar with the source code, where `lua_setupvalue` comes from? There is no such a method. Could I ask you please, add it for me? Maybe later, if you are busy at the moment.

**Comment by daurnimator** [comment]
> Hmm, I'm not familiar with the source code, where lua_setupvalue comes from? There is no such a method. Could I ask you please, add it for me? Maybe later, if you are busy at the moment.

Ah, looks like I never bound it: https://github.com/daurnimator/lua.vm.js/blob/4e3fd0341205b6bdecf74de80ea94e5d5e53013a/src/lua.js#L137
Should be simple to add it.

However, I'm not really maintaining lua.vm.js right now: I've been working on http://fengari.io/ instead.

**Comment by egordorichev** [comment]
http://fengari.io/ doesn't seem to have a lot of docs, hah :) Could you write it just for me? Thanks, and sorry for distracting you.

**Comment by daurnimator** [comment]
> http://fengari.io/ doesn't seem to have a lot of docs, hah :)

Yeah docs are missing, but I hope this might catch an inquisitive eye:
Right click => view source => notice `<script src="/static/lua/web-cli.lua" type="text/lua" async></script>`

Docs are spread across components such as https://github.com/fengari-lua/fengari#fengari and https://github.com/fengari-lua/fengari-interop#js-library-for-fengari

> Could you write it just for me?

Write what?

**Comment by egordorichev** [comment]
> Write what?
**lua_setupvalue**

**Comment by daurnimator** [comment]
Done now in master (I think).

**Comment by egordorichev** [comment]
Something went wrong:

![screenshot from 2017-09-05 16-36-00](https://user-images.githubusercontent.com/7851390/30063756-586015c2-9258-11e7-90cb-b8a74158cda7.png)

**Comment by daurnimator** [comment]
> Something went wrong:

Doing what?

**Comment by egordorichev** [comment]
I just updated `lua.vm.js`. Did not change the code.

**Comment by daurnimator** [comment]
> I just updated lua.vm.js. Did not change the code.

I guess something changed with emscripten..... I can force-unpush the commit for now?
I don't have time to debug something like this now.

**Comment by egordorichev** [comment]
Ok, sure. Please, fix it, when you have time.
